### ISSUE TITLE
.

### ISSUE THREAD

**Issue by muhiris** [KhiemLikestoProgram/khiemlikestoprogram.github.io#1]
Let's Build Community Follow Back Kindly.

**Comment by KhiemLikestoProgram** [comment]
What are you doing here
Why
I don't need people helping me
Why??????

**Comment by KhiemLikestoProgram** [comment]
Oh
Do You Play Deltarune
This Is What The Queen Style Of Talking Is Like

**Comment by muhiris** [comment]
LOL .. I just wanted to get more followers.

**Comment by KhiemLikestoProgram** [comment]
Ok. You need followers for what though?

**Comment by muhiris** [comment]
It's important in order to get your repositories in search results and getting jobs within github community

**Comment by KhiemLikestoProgram** [comment]
Ok then. But I don't need followers so don't show someone my account, ok? I'll follow you later
